In [9]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
#import seaborn as sns

df=pd.read_csv(r'C:/Python/datasets/Twitch_game_data_Original.csv',encoding='cp1252')


df.head()

,Rank,Game,Month,Year,Hours_watched,Hours_Streamed,Peak_viewers,Peak_channels,Streamers,Avg_viewers,Avg_channels,Avg_viewer_ratio
0,1,League of Legends,1,2016,94377226,1362044 hours,530270,2903,129172,127021,1833,69.29
1,2,Counter-Strike: Global Offensive,1,2016,47832863,830105 hours,372654,2197,120849,64378,1117,57.62
2,3,Dota 2,1,2016,45185893,433397 hours,315083,1100,44074,60815,583,104.26
3,4,Hearthstone,1,2016,39936159,235903 hours,131357,517,36170,53749,317,169.29
4,5,Call of Duty: Black Ops III,1,2016,16153057,1151578 hours,71639,3620,214054,21740,1549,14.03

In [10]:
df.dtypes

Rank                  int64
Game                 object
Month                 int64
Year                  int64
Hours_watched         int64
Hours_Streamed       object
Peak_viewers          int64
Peak_channels         int64
Streamers             int64
Avg_viewers           int64
Avg_channels          int64
Avg_viewer_ratio    float64
dtype: object

In [11]:
p = df['Hours_Streamed'].str
df['Hours_Streamed'] = np.where(p.endswith(' hours'),p.replace(' hours','',regex=True),p)
df.head()

,Rank,Game,Month,Year,Hours_watched,Hours_Streamed,Peak_viewers,Peak_channels,Streamers,Avg_viewers,Avg_channels,Avg_viewer_ratio
0,1,League of Legends,1,2016,94377226,1362044,530270,2903,129172,127021,1833,69.29
1,2,Counter-Strike: Global Offensive,1,2016,47832863,830105,372654,2197,120849,64378,1117,57.62
2,3,Dota 2,1,2016,45185893,433397,315083,1100,44074,60815,583,104.26
3,4,Hearthstone,1,2016,39936159,235903,131357,517,36170,53749,317,169.29
4,5,Call of Duty: Black Ops III,1,2016,16153057,1151578,71639,3620,214054,21740,1549,14.03

In [14]:
df['Hours_Streamed'] = df.Hours_Streamed.astype(np.int64)

In [15]:
df.dtypes

Rank                  int64
Game                 object
Month                 int64
Year                  int64
Hours_watched         int64
Hours_Streamed        int64
Peak_viewers          int64
Peak_channels         int64
Streamers             int64
Avg_viewers           int64
Avg_channels          int64
Avg_viewer_ratio    float64
dtype: object

In [18]:
df['Game'] = df['Game'].astype(str).str.replace('<U+00E9>', 'e', regex=True)

In [44]:
print(df.loc[df['Game'] == 'Destiny'])

      Rank     Game  Month  Year  Hours_watched  Hours_Streamed  Peak_viewers  \
12      13  Destiny      1  2016        5892573          551615         18783
211     12  Destiny      2  2016        5548885          533523         24859
417     18  Destiny      3  2016        4295202          450776         98649
611     12  Destiny      4  2016        5853751          568842         83004
813     14  Destiny      5  2016        4983341          507901         22235
1012    13  Destiny      6  2016        5213983          493371        234438
1211    12  Destiny      7  2016        5755249          544862         82354
1410    11  Destiny      8  2016        6590676          592357        141860
1607     8  Destiny      9  2016       10026708          783390        140031
1807     8  Destiny     10  2016        9845775          822454         92396
2011    12  Destiny     11  2016        6263862         1126457         23631
2210    11  Destiny     12  2016        6434867         1481157         28192
2412    13  Destiny      1  2017        6409419         1142731         20422
2615    16  Destiny      2  2017        5733241          870850         61286
2813    14  Destiny      3  2017        6143691          886549        107657
3009    10  Destiny      4  2017        7791063          944296         24898
3214    15  Destiny      5  2017        6361058          789219         22715
3417    18  Destiny      6  2017        5121678          636346         22483
3616    17  Destiny      7  2017        3872941          573138         17719
3827    28  Destiny      8  2017        2524522          379360         14676
4099   100  Destiny      9  2017         417840           74816         12425

      Peak_channels  Streamers  Avg_viewers  Avg_channels  Avg_viewer_ratio
12             1741      60340         7930           742             10.68
211            1851      54425         7984           767             10.40
417            1768      49191         5780           606              9.53
611            2489      57812         8141           791             10.29
813            1652      58174         6707           683              9.81
1012           1494      56812         7251           686             10.57
1211           1443      62686         7745           733             10.56
1410           1717      65024         8870           797             11.13
1607           5970      90958        13945          1089             12.80
1807           2568      85869        13251          1106             11.97
2011           4342      73505         8711          1566              5.56
2210           4151      28010         8660          1993              4.34
2412           3088      77673         8626          1537              5.61
2615           2901      60912         8544          1297              6.58
2813           4818      55717         8268          1193              6.93
3009           2872      63558        10835          1313              8.25
3214           2296      67862         8561          1062              8.06
3417           1931      55773         7123           885              8.05
3616           1781      51941         5212           771              6.76
3827           1486      37495         3397           510              6.65
4099            789      17135          581           104              5.58

In [24]:
print(df.loc[df['Game'] == 'Pok<U+00E9>mon Sword/Shield'])

       Rank                         Game  Month  Year  Hours_watched  \
9110    111  Pok<U+00E9>mon Sword/Shield     10  2019         597737
9206      7  Pok<U+00E9>mon Sword/Shield     11  2019       27173037
9418     19  Pok<U+00E9>mon Sword/Shield     12  2019       10322209
9629     30  Pok<U+00E9>mon Sword/Shield      1  2020        4657586
9838     39  Pok<U+00E9>mon Sword/Shield      2  2020        3183977
10048    49  Pok<U+00E9>mon Sword/Shield      3  2020        2876384
10254    55  Pok<U+00E9>mon Sword/Shield      4  2020        2754491
10464    65  Pok<U+00E9>mon Sword/Shield      5  2020        2439201
10633    34  Pok<U+00E9>mon Sword/Shield      6  2020        6047136
10852    53  Pok<U+00E9>mon Sword/Shield      7  2020        3789891
11055    56  Pok<U+00E9>mon Sword/Shield      8  2020        3169607
11278    79  Pok<U+00E9>mon Sword/Shield      9  2020        1795874
11437    38  Pok<U+00E9>mon Sword/Shield     10  2020        5725244
11643    44  Pok<U+00E9>mon Sword/Shield     11  2020        5449862
11862    63  Pok<U+00E9>mon Sword/Shield     12  2020        3037611
12050    51  Pok<U+00E9>mon Sword/Shield      1  2021        4121232
12252    53  Pok<U+00E9>mon Sword/Shield      2  2021        3961694
12459    60  Pok<U+00E9>mon Sword/Shield      3  2021        3976022
12659    60  Pok<U+00E9>mon Sword/Shield      4  2021        3885515
12865    66  Pok<U+00E9>mon Sword/Shield      5  2021        3505314
13067    68  Pok<U+00E9>mon Sword/Shield      6  2021        3222405
13265    66  Pok<U+00E9>mon Sword/Shield      7  2021        2956760
13468    69  Pok<U+00E9>mon Sword/Shield      8  2021        3394809
13682    83  Pok<U+00E9>mon Sword/Shield      9  2021        2520501
13881    82  Pok<U+00E9>mon Sword/Shield     10  2021        2549342
14102   103  Pok<U+00E9>mon Sword/Shield     11  2021        1832542
14399   200  Pok<U+00E9>mon Sword/Shield     12  2021         615725

       Hours_Streamed  Peak_viewers  Peak_channels  Streamers  Avg_viewers  \
9110             1414         45429             58        278          804
9206           501750        187166           4414      32492        37792
9418           291595         63077            956      22867        13892
9629           188772         34159            539      15243         6268
9838           132270         15849            387      10495         4581
10048          112653         18471            299       9303         3871
10254           93678         67743            257       6495         3831
10464           99805         12536            240       7190         3282
10633          193517        115043           2345      16206         8410
10852          139507         15223            364      10238         5100
11055          108463         99618            254       7952         4265
11278           92037         17366            367       7209         2497
11437          196082         69601           1855      15843         7705
11643          192604         39612            574      15076         7579
11862          142114         23832            362      11567         4088
12050          163571         70186            400      12944         5546
12252          155880         58054            946      13454         5904
12459          171743         61936            418      14573         5351
12659          148127         37644            367      12341         5404
12865          139212         33664            340      11264         4717
13067          136225         16454            341      10927         4481
13265          127883         58972            321      10642         3979
13468          128019         63857            448      10648         4569
13682          121923         18315            292      10065         3505
13881          118809         16031            279       9430         3431
14102           95268         13346            306       9077         2548
14399           42291          8878            106       4411          828

       Avg_channels  Avg_viewer_ratio
9110              1            422.73
9206            697             54.16
9418            392             35.40
9629            254             24.67
9838            190             24.07
10048           151             25.53
10254           130             29.40
10464           134             24.44
10633           269             31.25
10852           187             27.17
11055           145             29.22
11278           128             19.51
11437           263             29.20
11643           267             28.30
11862           191             21.37
12050           220             25.20
12252           232             25.42
12459           231             23.15
12659           206             26.23
12865           187             25.18
13067           189             23.66
13265           172             23.12
13468           172             26.52
13682           169             20.67
13881           159             21.46
14102           132             19.24
14399            56             14.56

,Rank,Game,Month,Year,Hours_watched,Hours_Streamed,Peak_viewers,Peak_channels,Streamers,Avg_viewers,Avg_channels,Avg_viewer_ratio
0,1,League of Legends,1,2016,94377226,1362044,530270,2903,129172,127021,1833,69.29
1,2,Counter-Strike: Global Offensive,1,2016,47832863,830105,372654,2197,120849,64378,1117,57.62
2,3,Dota 2,1,2016,45185893,433397,315083,1100,44074,60815,583,104.26
3,4,Hearthstone,1,2016,39936159,235903,131357,517,36170,53749,317,169.29
4,5,Call of Duty: Black Ops III,1,2016,16153057,1151578,71639,3620,214054,21740,1549,14.03
...,...,...,...,...,...,...,...,...,...,...,...,...
14395,196,Garry's Mod,12,2021,630902,21753,24951,99,3537,849,29,29.00
14396,197,Call of Duty: Black Ops Cold War,12,2021,622497,223641,26559,654,25366,837,300,2.78
14397,198,Noita,12,2021,620983,13935,27826,41,1961,835,18,44.56
14398,199,Pro Soccer Online,12,2021,619859,606,36182,20,84,834,0,1022.87
14399,200,Pokemon Sword/Shield,12,2021,615725,42291,8878,106,4411,828,56,14.56

In [92]:
df.replace(to_replace ='Pok<U+00E9>mon Sword/Shield',
               value ='Pokemon Sword/Shield',inplace=True)

df.replace(to_replace ='Pok<U+00E9>mon Omega Ruby/Alpha Sapphire',
               value ='Pokemon Omega Ruby/Alpha Sapphire',inplace=True)
           
df.replace(to_replace ='Pok<U+00E9>mon Red/Blue',
               value ='Pokemon Red/Blue',inplace=True)

df.replace(to_replace ='Pok<U+00E9>mon Yellow',
               value ='Pokemon Yellow',inplace=True)

df.replace(to_replace ='Pok<U+00E9>mon FireRed/LeafGreen',
               value ='Pokemon FireRed/LeafGreen',inplace=True)

df.replace(to_replace ='Pokk<U+00E9>n Tournament',
               value ='Pokken Tournament',inplace=True)

df.replace(to_replace ='Pok<U+00E9>mon Crystal',
               value ='Pokemon Crystal',inplace=True)

df.replace(to_replace ='Pok<U+00E9>mon Sun/Moon',
               value ='Pokemon Sun/Moon',inplace=True)

df.replace(to_replace ='Pok<U+00E9>mon GO',
               value ='Pokemon GO',inplace=True)

df.replace(to_replace ='Pok<U+00E9>mon Trading Card Game Online',
               value ='Pokemon Trading Card Game Online',inplace=True)

df.replace(to_replace ='Pok<U+00E9>mon Emerald',
               value ='Pokemon Emerald',inplace=True)

df.replace(to_replace ='Pok<U+00E9>mon Trading Card Game',
               value ='Trading Card Game',inplace=True)

df.replace(to_replace ='Pok<U+00E9>mon HeartGold/SoulSilver',
               value ='Pokemon HeartGold/SoulSilver',inplace=True)

df.replace(to_replace ='Pok<U+00E9>mon Black/White Version 2',
               value ='Pokemon Black/White Version 2',inplace=True)

df.replace(to_replace ='Pok<U+00E9>mon Ultra Sun/Ultra Moon',
               value ='Pokemon Ultra Sun/Ultra Moon',inplace=True)

df.replace(to_replace ='Pok<U+00E9>mon Quest',
               value ='Pokemon Quest',inplace=True)

df.replace(to_replace ="Pok<U+00E9>mon: Let's Go, Pikachu!",
               value ="Pokemon: Let's Go, Pikachu!", inplace=True)
           
df.replace(to_replace ='Pok<U+00E9>mon Stadium 2',
               value ='Pokemon Stadium 2',inplace=True)

df.replace(to_replace ='Pok<U+00E9>mon Mystery Dungeon: Rescue Team DX',
               value ='Pokemon Mystery Dungeon: Rescue Team DX',inplace=True)

df.replace(to_replace ='Pok<U+00E9>mon X/Y',
               value ='Pokemon X/Y',inplace=True)

df.replace(to_replace ='Pok<U+00E9>mon Platinum',
               value ='Pokemon Platinum',inplace=True)

df.replace(to_replace ='Pok<U+00E9>mon Unite',
               value ='Pokemon Unite',inplace=True)

df.replace(to_replace ='Pok<U+00E9>mon Brilliant Diamond/Shining Pearl',
               value ='Pokemon Brilliant Diamond/Shining Pearl',inplace=True)

df.replace(to_replace ='New Pok<U+00E9>mon Snap',
               value ='New Pokemon Snap',inplace=True)

df.replace(to_replace ='Pok<U+00E9>mon Ruby/Sapphire',
               value ='Pokemon Ruby/Sapphire',inplace=True)

In [86]:
print(df.loc[df['Game'] == 'Pokemon Red/Blue'])

      Rank              Game  Month  Year  Hours_watched  Hours_Streamed  \
78      79  Pokemon Red/Blue      1  2016         456370            3276
321    122  Pokemon Red/Blue      2  2016         192855            4838
568    169  Pokemon Red/Blue      3  2016         130912            6335
947    148  Pokemon Red/Blue      5  2016         142057            2926
1193   194  Pokemon Red/Blue      6  2016          95558            2717
1267    68  Pokemon Red/Blue      7  2016         514488            6209
1498    99  Pokemon Red/Blue      8  2016         301344            9192
2798   199  Pokemon Red/Blue      2  2017         146092            3717

      Peak_viewers  Peak_channels  Streamers  Avg_viewers  Avg_channels  \
78          185106             40        540          614             4
321          20162             53        865          277             6
568           4401             34       1043          176             8
947           3218             13        524          191             3
1193         12615             14        476          132             3
1267        150951             31       1117          692             8
1498          5698             34       1128          405            12
2798          1220             16        363          217             5

      Avg_viewer_ratio
78              139.31
321              39.86
568              20.66
947              48.55
1193             35.17
1267             82.86
1498             32.78
2798             39.30

In [75]:
#print(df.loc[df['Game'] == 'Fortnite'])

In [67]:
#df[8644:8828]

In [93]:
pd.options.display.max_rows = 270
df = df[df['Game'].str.contains('Pok')]
print(df['Game'])

21                                         Poker
50             Pokemon Omega Ruby/Alpha Sapphire
78                              Pokemon Red/Blue
79                                Pokemon Yellow
226                                        Poker
252            Pokemon Omega Ruby/Alpha Sapphire
321                             Pokemon Red/Blue
377                    Pokemon FireRed/LeafGreen
422                                        Poker
444            Pokemon Omega Ruby/Alpha Sapphire
450                            Pokken Tournament
568                             Pokemon Red/Blue
579                              Pokemon Crystal
617                                        Poker
644            Pokemon Omega Ruby/Alpha Sapphire
757                            Pokken Tournament
765                              Pokemon Crystal
815                                        Poker
844            Pokemon Omega Ruby/Alpha Sapphire
947                             Pokemon Red/Blue
1030                                       Poker
1039           Pokemon Omega Ruby/Alpha Sapphire
1193                            Pokemon Red/Blue
1209                                  Pokemon GO
1227                                       Poker
1242           Pokemon Omega Ruby/Alpha Sapphire
1267                            Pokemon Red/Blue
1354                           Pokken Tournament
1420                                       Poker
1422                                  Pokemon GO
1431           Pokemon Omega Ruby/Alpha Sapphire
1498                            Pokemon Red/Blue
1511                              Pokemon Yellow
1599                   Pokemon FireRed/LeafGreen
1611                                       Poker
1635           Pokemon Omega Ruby/Alpha Sapphire
1665                                  Pokemon GO
1827                                       Poker
1843           Pokemon Omega Ruby/Alpha Sapphire
1945                                  Pokemon GO
2021                            Pokemon Sun/Moon
2029                                       Poker
2065           Pokemon Omega Ruby/Alpha Sapphire
2188                   Pokemon FireRed/LeafGreen
2221                            Pokemon Sun/Moon
2223                                       Poker
2424                                       Poker
2429                            Pokemon Sun/Moon
2478                             Pokemon Emerald
2622                                       Poker
2632                            Pokemon Sun/Moon
2798                            Pokemon Red/Blue
2824                                       Poker
2856                            Pokemon Sun/Moon
3025                                       Poker
3054                            Pokemon Sun/Moon
3217                                       Poker
3260                            Pokemon Sun/Moon
3383            Pokemon Trading Card Game Online
3431                                       Poker
3458                            Pokemon Sun/Moon
3633                                       Poker
3662                            Pokemon Sun/Moon
3688                Pokemon HeartGold/SoulSilver
3732                                  Pokemon GO
3822                                       Poker
3848                            Pokemon Sun/Moon
4022                                       Poker
4061                            Pokemon Sun/Moon
4238                                       Poker
4271                            Pokemon Sun/Moon
4424                                       Poker
4438                Pokemon Ultra Sun/Ultra Moon
4502                            Pokemon Sun/Moon
4627                                       Poker
4647                Pokemon Ultra Sun/Ultra Moon
4827                                       Poker
4860                Pokemon Ultra Sun/Ultra Moon
4881               Pokemon Black/White Version 2
5018                                       Poker
5067                Pokemon Ultra Sun/Ultra Moon
5231                                       Poker
5277                Pokemon Ultra Sun/Ultra Moon
5427                                       Poker
5477                Pokemon Ultra Sun/Ultra Moon
5619                                       Poker
5686                Pokemon Ultra Sun/Ultra Moon
5830                                       Poker
5886                Pokemon Ultra Sun/Ultra Moon
5982                               Pokemon Quest
6026                                       Poker
6065                Pokemon Ultra Sun/Ultra Moon
6227                                       Poker
6263                Pokemon Ultra Sun/Ultra Moon
6423                                       Poker
6476                Pokemon Ultra Sun/Ultra Moon
6630                                       Poker
6692                Pokemon Ultra Sun/Ultra Moon
6778                Pokemon HeartGold/SoulSilver
6811                 Pokemon: Let's Go, Pikachu!
6834                                       Poker
6915                Pokemon Ultra Sun/Ultra Moon
7028                 Pokemon: Let's Go, Pikachu!
7029                                       Poker
7170                Pokemon Ultra Sun/Ultra Moon
7226                                       Poker
7264                 Pokemon: Let's Go, Pikachu!
7427                                       Poker
7493                 Pokemon: Let's Go, Pikachu!
7594                Pokemon Ultra Sun/Ultra Moon
7628                                       Poker
7694                 Pokemon: Let's Go, Pikachu!
7835                                       Poker
7926                 Pokemon: Let's Go, Pikachu!
7977                            Prominence Poker
7990                Pokemon Ultra Sun/Ultra Moon
8022                                       Poker
8117                 Pokemon: Let's Go, Pikachu!
8192                Pokemon Ultra Sun/Ultra Moon
8239                                       Poker
8275                 Pokemon: Let's Go, Pikachu!
8304                             Pokemon Crystal
8373                Pokemon Ultra Sun/Ultra Moon
8433                                       Poker
8509                 Pokemon: Let's Go, Pikachu!
8593                Pokemon Ultra Sun/Ultra Moon
8626                                       Poker
8706                 Pokemon: Let's Go, Pikachu!
8743                Pokemon Ultra Sun/Ultra Moon
8825                                       Poker
8953                 Pokemon: Let's Go, Pikachu!
8978               Pokemon Black/White Version 2
9037                                       Poker
9110                        Pokemon Sword/Shield
9127                 Pokemon: Let's Go, Pikachu!
9197                           Pokemon Stadium 2
9206                        Pokemon Sword/Shield
9237                                       Poker
9352                 Pokemon: Let's Go, Pikachu!
9418                        Pokemon Sword/Shield
9431                                       Poker
9629                        Pokemon Sword/Shield
9635                                       Poker
9729                                 Pokemon X/Y
9776                       Pokemon Ruby/Sapphire
9831                                       Poker
9838                        Pokemon Sword/Shield
10028                                      Poker
10048                       Pokemon Sword/Shield
10101    Pokemon Mystery Dungeon: Rescue Team DX
10229                                      Poker
10254                       Pokemon Sword/Shield
10425                                      Poker
10464                       Pokemon Sword/Shield
10633                       Pokemon Sword/Shield
10638                                      Poker
10782               Pokemon HeartGold/SoulSilver
10797                            Pokemon Emerald
10827                                      Poker
10852                       Pokemon Sword/Shield
10923                                 Pokemon GO
10934                           Pokemon Platinum
10976                            Pokemon Emerald
11032                                      Poker
11055                       Pokemon Sword/Shield
11119                                 Pokemon GO
11196               Pokemon HeartGold/SoulSilver
11228                                      Poker
11278                       Pokemon Sword/Shield
11332                                 Pokemon GO
11390                           Pokemon Platinum
11437                       Pokemon Sword/Shield
11442                                      Poker
11536                                 Pokemon GO
11573                           Pokemon Platinum
11637                                      Poker
11643                       Pokemon Sword/Shield
11741                                 Pokemon GO
11842                                      Poker
11862                       Pokemon Sword/Shield
11933                                 Pokemon GO
11946                  Pokemon FireRed/LeafGreen
11974               Pokemon HeartGold/SoulSilver
12033                                      Poker
12050                       Pokemon Sword/Shield
12134                                 Pokemon GO
12158                           Pokemon Platinum
12190               Pokemon HeartGold/SoulSilver
12239                                      Poker
12252                       Pokemon Sword/Shield
12326                                 Pokemon GO
12376                  Pokemon FireRed/LeafGreen
12439                                      Poker
12459                       Pokemon Sword/Shield
12532                           Pokemon Platinum
12539                                 Pokemon GO
12636                                      Poker
12659                       Pokemon Sword/Shield
12753                           New Pokemon Snap
12758                                 Pokemon GO
12798                           Pokemon Platinum
12844                                      Poker
12859                           New Pokemon Snap
12865                       Pokemon Sword/Shield
12976                                 Pokemon GO
13032                  Pokemon FireRed/LeafGreen
13053                                      Poker
13067                       Pokemon Sword/Shield
13137                           Pokemon Platinum
13144                                 Pokemon GO
13168                              Pokemon Unite
13221                              Pokemon Unite
13251                                      Poker
13265                       Pokemon Sword/Shield
13314                                 Pokemon GO
13390                           Pokemon Platinum
13437                              Pokemon Unite
13442                                      Poker
13468                       Pokemon Sword/Shield
13553                            Pokemon Emerald
13578                                 Pokemon GO
13637                                      Poker
13665                              Pokemon Unite
13682                       Pokemon Sword/Shield
13757                                 Pokemon GO
13853                                      Poker
13869                              Pokemon Unite
13881                       Pokemon Sword/Shield
13956                                 Pokemon GO
14013    Pokemon Brilliant Diamond/Shining Pearl
14050                                      Poker
14102                       Pokemon Sword/Shield
14108                              Pokemon Unite
14194                                 Pokemon GO
14222    Pokemon Brilliant Diamond/Shining Pearl
14248                                      Poker
14303                              Pokemon Unite
14379                  Pokemon FireRed/LeafGreen
14386                                 Pokemon GO
14399                       Pokemon Sword/Shield
Name: Game, dtype: object